### ISSUE TITLE
Error in optim(theta0, fn, gr = gn, lower = rep(0, ns), upper = rep(Inf,  :    L-BFGS-B needs finite values of 'fn'

### ISSUE THREAD

**Issue by lijxug** [TaoYang-dev/AdRoit#1]
Hi, I was testing your tool using my dataset(smart-seq protocol) and I got a matrix full of NA. I tried to debug the function AdRoit.est() and got the error message written in title. 
I guess this might be due to the counts which may be too large at some points during the optimization process. 
My range of bulk rawcount matrix to test is 0-152882096.

Hope that's helpful and this issue can be fixed. ;)

**Comment by yubailibra** [comment]
Hi, the error could be due to the fact that SmartSeq data (RPM/FPM type) are not integers. You may try to round the input data. This patch is implemented in the reference builder now.

**Comment by lijxug** [comment]
Great, I'll try it out!
